---
- name: install core packages for virtual machines
  hosts: "{{ hosts }}"
  become: yes
  roles:
    - mdsketch.teleport
  vars:
    teleport_ssh_labels:
      - k: "access"
        v: "homelab-vm"
    teleport_auth_token: "{{ teleport_auth_token }}"
    teleport_ca_pin: "sha256:fd6a4106f2f644b238f8efd5673ff73b85a270cd95d650a16cb2a62afaf8980e"
    teleport_proxy_server: "teleport.facha.dev:443"
    teleport_config_template: "../templates/teleport/teleport.yaml.j2"
    #teleport_auth_server: ""