---
- name: install core packages for virtual machines
  hosts: "{{ hosts }}"
  become: yes
  roles:
    - mdsketch.teleport
  vars:
    teleport_ssh_labels:
      - k: "access"
        v: "{{ access_tag }}"
    teleport_auth_token: "{{ teleport_auth_token }}"
    teleport_proxy_server: "teleport.facha.dev:443"
    teleport_config_template: "../templates/teleport/teleport.yaml.j2"
    teleport_version: 15.4.0