- name: Configure SSH for Key-Based Authentication Only
  hosts: lab
  become: true

  tasks:
    - name: Ensure SSH PasswordAuthentication is set to no
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Restart sshd to apply changes
      ansible.builtin.service:
        name: sshd
        state: restarted
