---
- name: Add CA certificate for SSL decryption
  hosts: all
  become: yes
  tasks:
    - name: Ensure the CA certificate is present in the system trust store
      ansible.builtin.copy:
        src: "./ca/SSL_CA.pem"
        dest: "/usr/local/share/ca-certificates/SSL_CA.crt"
        owner: "root"
        group: "root"
        mode: "0644"
      register: ca_cert_result

    - name: Update the certificate database
      ansible.builtin.command:
        cmd: "update-ca-certificates"
      when: ca_cert_result.changed
