- name: Update and Upgrade System Packages
  hosts: lab
  become: yes

  tasks:
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: yes

    - name: Dist-upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
